version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./todo_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./todo_frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
