# Backend Dockerfile
# Use official Python image as the base
FROM python:3.10-slim


# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install dependencies
COPY todo_backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the backend project into the container
COPY todo_backend/ .

# Expose the Django default port
EXPOSE 8000

# Run Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
